### ISSUE TITLE
Instant crash when launching game configuration

### ISSUE THREAD

**Issue by AireagoirSteam** [FaithLV/spectabis-next#32]
When trying to configure any added game the front end crashes. Nkt sure if have a log but I will look.

**Comment by FaithLV** [comment]
Thanks for trying to run this!  Please, keep in mind `spectabis-next` is in **very early development** state.

I just created a quick guide for providing logs and additional information. Please update your post according to this guide. https://github.com/FaithLV/spectabis-next/blob/master/CONTRIBUTING.md
