### ISSUE TITLE
PCSX2 crashes on launching with invalid argument error

### ISSUE THREAD

**Issue by PrudentMantis** [FaithLV/spectabis-next#34]
First off, this could very well be user error. I'm not sure I've got the PCSX2 Configuration Folder set correctly - it _is_ supposed to be the 'inis' folder in the PCSX2 Root Directory, assuming I'm not using an installer version but have instead just downloaded a 1.7.0 build, right? I couldn't find any documentation that specified.

Assuming so, and that I'm not a _complete_ idiot:

Trying to either run or configure a game once added throws up the following error message from what seems to be **PCSX2**, _not_ Spectabis: Unknown long option 'cfgpathC'. After clicking OK, the PCSX2 Commandline Options dialogue comes up. While these two dialogues are up, Spectabis Next has 'Game is running' shown in its window, with the option to click 'Stop Game'. Once the PCSX2 Commandline Options screen is closed, Spectabis Next doesn't crash, it simply returns to the library. This happens with any game in my Library.

Both PCSX2, the game image files, and Spectabis Next are all located on a non-OS drive, if that matters.

OS: Windows 10 Pro
OS Version: 2004
Spectabis Version: 0.2.0-20201119.1

Full Console dump follows, from launch to exit:
[ConfigurationLoader] Getting default config for 'SpectabisLib.Configuration.UIConfig'
[ConfigurationLoader] Loading 'C:\Users\chir_\.spectabis\\spectabis.json
[ConfigurationLoader] Loading 'C:\Users\chir_\.spectabis\\directory.json
[ConfigurationLoader] Getting default config for 'SpectabisLib.Configuration.TextConfig'
[PagePreloader] PagePreloader: 2683661
[Telemetry] Creating telemetry client
[Telemetry] Telemetry Enabled
[PagePreloader] Preloading page: SpectabisUI.Pages.GameLibrary
[ServiceClient] Creating client to service at 'https://spectabis-api-eu.azurewebsites.net/api/'
[PageFactory] Creating new SpectabisUI.Pages.GameLibrary
[PagePreloader] Preloading page: SpectabisUI.Pages.Settings
[PageFactory] Creating new SpectabisUI.Pages.Settings
[PagePreloader] Preloading page: SpectabisUI.Pages.CreateProfile
[LocalDatabaseProvider] Building game database
[LocalDatabaseProvider] GameDatabaseProvider: Reading PCSX2 game database from 'Resources/gamedatabase.csv'
[LocalDatabaseProvider] Building game index
[Telemetry] Flusing telemetry data from memory
[PageFactory] Creating new SpectabisUI.Pages.CreateProfile
[PageNavigator] Generating navigation icon for SpectabisUI.Pages.GameLibrary
[PageNavigator] Generating navigation icon for SpectabisUI.Pages.Settings
[PageNavigator] Generating navigation icon for SpectabisUI.Pages.CreateProfile
[Program] Starting Spectabis '0.2.0.0'
[BitmapLoader] Failed to load boxart for '88426176-8470-46af-9ad6-bc1d9409db47'
[BitmapLoader] Unable to load bitmap from provided data
[BitmapLoader] Failed to load boxart for 'de650e18-4e32-4e7b-bdd3-d6d6f32a7843'
[BitmapLoader] Unable to load bitmap from provided data
[GameLibrary.xaml] Launching Star Wars - Jedi Starfighter
[GameLauncherPCSX2] Emulator path for 'Star Wars - Jedi Starfighter' loaded from directory.json
[ProfileFileSystem] Overwriting profile json '0d43cefc-b34e-49cf-bfc1-2b88674f1856'
[GameRunning.xaml] Game running:Star Wars - Jedi Starfighter with processId '8892'
[PageFactory] Creating new SpectabisUI.Pages.GameRunning
[ProfileFileSystem] Overwriting profile json '0d43cefc-b34e-49cf-bfc1-2b88674f1856'

**Comment by FaithLV** [comment]
Hi, thanks for taking an interest!

The release section is a bit misleading, as they are not released automatically and the one you are using is from November.
Regardless, could you please try with the current latest version and verify this still happens?

https://dev.azure.com/Spectabis/SpectabisNext/_build/results?buildId=333&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by PrudentMantis** [comment]
Yeah, still happens unfortunately. Here's the console dump:

[/home/vsts/work/1/s/src/SpectabisNext/Services/ConfigurationLoader.cs] Getting default config for 'SpectabisLib.Configuration.UIConfig'
[/home/vsts/work/1/s/src/SpectabisNext/Services/ConfigurationLoader.cs] Loading 'C:\Users\chir_\.spectabis\\spectabis.json
[/home/vsts/work/1/s/src/SpectabisNext/Services/ConfigurationLoader.cs] Loading 'C:\Users\chir_\.spectabis\\directory.json
[/home/vsts/work/1/s/src/SpectabisNext/Services/ConfigurationLoader.cs] Getting default config for 'SpectabisLib.Configuration.TextConfig'
[/home/vsts/work/1/s/src/SpectabisNext/Services/PagePreloader.cs] PagePreloader: 27795493
[Telemetry] Creating telemetry client
[Telemetry] Attaching exception telemetry handlers
[/home/vsts/work/1/s/src/SpectabisNext/Services/PagePreloader.cs] Preloading page: SpectabisUI.Pages.GameLibrary
[ServiceClient] Creating client to service at 'https://spectabis-api-eu.azurewebsites.net/api/'
[/home/vsts/work/1/s/src/SpectabisUI/Factories/PageFactory.cs] Creating new SpectabisUI.Pages.GameLibrary
[/home/vsts/work/1/s/src/SpectabisNext/Services/PagePreloader.cs] Preloading page: SpectabisUI.Pages.Settings
[/home/vsts/work/1/s/src/SpectabisUI/Factories/PageFactory.cs] Creating new SpectabisUI.Pages.Settings
[/home/vsts/work/1/s/src/SpectabisNext/Services/PagePreloader.cs] Preloading page: SpectabisUI.Pages.CreateProfile
[/home/vsts/work/1/s/src/SpectabisLib/Services/LocalDatabaseProvider.cs] Building game database
[/home/vsts/work/1/s/src/SpectabisLib/Services/LocalDatabaseProvider.cs] GameDatabaseProvider: Reading PCSX2 game database from 'Resources/gamedatabase.csv'
[/home/vsts/work/1/s/src/SpectabisLib/Services/LocalDatabaseProvider.cs] Building game index
[Telemetry] Flusing telemetry data from memory
[/home/vsts/work/1/s/src/SpectabisUI/Factories/PageFactory.cs] Creating new SpectabisUI.Pages.CreateProfile
[/home/vsts/work/1/s/src/SpectabisNext/Services/PageNavigator.cs] Generating navigation icon for SpectabisUI.Pages.GameLibrary
[/home/vsts/work/1/s/src/SpectabisNext/Services/PageNavigator.cs] Generating navigation icon for SpectabisUI.Pages.Settings
[/home/vsts/work/1/s/src/SpectabisNext/Services/PageNavigator.cs] Generating navigation icon for SpectabisUI.Pages.CreateProfile
[/home/vsts/work/1/s/src/SpectabisNext/Program.cs] Starting Spectabis '0.2.0.0'
[/home/vsts/work/1/s/src/SpectabisNext/Services/BitmapLoader.cs] Failed to load boxart for '88426176-8470-46af-9ad6-bc1d9409db47'
[/home/vsts/work/1/s/src/SpectabisNext/Services/BitmapLoader.cs] Unable to load bitmap from provided data
[/home/vsts/work/1/s/src/SpectabisNext/Services/BitmapLoader.cs] Failed to load boxart for 'de650e18-4e32-4e7b-bdd3-d6d6f32a7843'
[/home/vsts/work/1/s/src/SpectabisNext/Services/BitmapLoader.cs] Unable to load bitmap from provided data
[/home/vsts/work/1/s/src/SpectabisUI/Pages/GameLibrary.xaml.cs] Launching Star Wars - Jedi Starfighter
[/home/vsts/work/1/s/src/SpectabisLib/Services/GameLauncherPCSX2.cs] Emulator path for 'Star Wars - Jedi Starfighter' loaded from directory.json
[/home/vsts/work/1/s/src/SpectabisLib/Services/ProfileFileSystem.cs] Overwriting profile json '0d43cefc-b34e-49cf-bfc1-2b88674f1856'
[/home/vsts/work/1/s/src/SpectabisUI/Pages/GameRunning.xaml.cs] Game running:Star Wars - Jedi Starfighter with processId '13304'
[/home/vsts/work/1/s/src/SpectabisUI/Factories/PageFactory.cs] Creating new SpectabisUI.Pages.GameRunning
[/home/vsts/work/1/s/src/SpectabisLib/Services/ProfileFileSystem.cs] Overwriting profile json '0d43cefc-b34e-49cf-bfc1-2b88674f1856'
[Telemetry] Flusing telemetry data from memory

**Comment by FaithLV** [comment]
Interesting and wierd!

Could you verify the directory `C:\Users\chir_\.spectabis\` exists?
Also, is your account username `chir_` or is it something else?

**Comment by PrudentMantis** [comment]
Yep to both! And PCSX2\inis\ is the correct folder for the config stuff, right?

**Comment by FaithLV** [comment]
Ah, good catch! It should be the `PCSX2`, not `PCSX2/inis/`

**Comment by PrudentMantis** [comment]
Damn, I hoped that would fix it. Still has the same problem after correcting that. I didn't delete the .spectabis folder, instead I edited directory.json to have the correct directory, and then when that didn't work I edited spectabis.json so it would run the first-time wizard again. Neither changed anything about the behaviour.

**Comment by PrudentMantis** [comment]
Going into the .spectabis\profiles\0d43cefc-b34e-49cf-bfc1-2b88674f1856\ folder, I get this in profile.json:

{
  "Id": "0d43cefc-b34e-49cf-bfc1-2b88674f1856",
  "Title": "Star Wars - Jedi Starfighter",
  "SerialNumber": "SLUS20293",
  "FilePath": "D:\\Games\\Emulated\\PS2\\Discs\\USA\\Star Wars - Jedi Starfighter (USA).iso",
  "EmulatorPath": null,
  "BoxArtPath": null,
  "LaunchOptions": 0,
  "Playtime": "00:00:58.0334889",
  "LastPlayed": "2021-02-08T20:13:01.8092626+10:00"
}

Is that correct? Should EmulatorPath be something other than null?

**Comment by FaithLV** [comment]
Yes, the `profile.json` looks fine. EmulatorPath **can and should** be null as it is used only for overriding emulator on per-game basis.

Anyway, I think I've nailed down the issue. Please confirm if the issue persists with this build. (Click on the artifacts button to view files)
https://dev.azure.com/Spectabis/SpectabisNext/_build/results?buildId=336&view=results

**Comment by FaithLV** [comment]
Please try this build.

https://dev.azure.com/Spectabis/SpectabisNext/_build/results?buildId=339&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by PrudentMantis** [comment]
Yep, that works perfectly! Sorry for not getting back to you earlier, I saw the email but was busy at the time and then promptly proceeded to forget about it entirely. Thanks for the help!
